package cli

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// WriteEnvFile writes KEY=VALUE lines to path with mode 0600. The
// umask is tightened before the open so a permissive umask on the
// calling shell doesn't race us to world-readable — by the time
// chmod runs the secrets are already on disk. Values with shell
// metacharacters get quoted so `source packyard.env` in a shell
// trivially round-trips, which is how users inspect these files
// during debugging.
func WriteEnvFile(path string, values map[string]string) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o700); err != nil {
		return fmt.Errorf("create config dir: %w", err)
	}

	oldUmask := umask(0o077)
	defer umask(oldUmask)

	f, err := os.OpenFile(path, os.O_WRONLY|os.O_CREATE|os.O_TRUNC, 0o600)
	if err != nil {
		return fmt.Errorf("open %s: %w", path, err)
	}
	defer f.Close()

	// Sort for deterministic output — makes diffs readable when
	// operators version the env file or compare two installs.
	keys := make([]string, 0, len(values))
	for k := range values {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	fmt.Fprintln(f, "# Generated by `packyard init`. Restart the service after edits.")
	for _, k := range keys {
		fmt.Fprintf(f, "%s=%s\n", k, shellQuote(values[k]))
	}

	// Explicit chmod even though we asked for 0600 on open, because
	// some filesystems (NFS, tmpfs with sloppy mount options) lose
	// the mode bit on create.
	if err := os.Chmod(path, 0o600); err != nil {
		return fmt.Errorf("chmod %s: %w", path, err)
	}
	return nil
}

// shellQuote wraps values containing whitespace, quotes, or shell
// metacharacters in single quotes, escaping any embedded single
// quotes. Values that are plain tokens get returned unquoted — keeps
// the env file readable for the common case.
func shellQuote(v string) string {
	if v == "" {
		return `""`
	}
	const safe = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789_.-/:@"
	for _, r := range v {
		if !strings.ContainsRune(safe, r) {
			return "'" + strings.ReplaceAll(v, "'", `'\''`) + "'"
		}
	}
	return v
}
